"""update videos status Enum

Revision ID: 5a4f27fff629
Revises: ef638bd9753a
Create Date: 2026-02-24 17:37:10.626324

"""
from alembic import op
import sqlalchemy as sa


revision = '5a4f27fff629'
down_revision = 'ef638bd9753a'
branch_labels = None
depends_on = None


def upgrade() -> None:

    # 1️⃣ crear el tipo enum
    op.execute("""
        CREATE TYPE video_status_enum AS ENUM (
            'PENDING_METADATA',
            'PROCESSING_METADATA',
            'AVAILABLE',
            'INVALID'
        )
    """)

    # 2️⃣ convertir la columna
    op.execute("""
        ALTER TABLE videos
        ALTER COLUMN status
        TYPE video_status_enum
        USING status::video_status_enum
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE videos
        ALTER COLUMN status
        TYPE VARCHAR(50)
    """)

    op.execute("DROP TYPE video_status_enum")
