"""add video table

Revision ID: d1d1d81f68d2
Revises: 1d11381e9cfe
Create Date: 2026-02-12 14:48:45.855744

"""
from alembic import op
import sqlalchemy as sa


revision = 'd1d1d81f68d2'
down_revision = '1d11381e9cfe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('codec', sa.String(length=50), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('has_audio', sa.Boolean(), nullable=True),
    sa.Column('audio_codec', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('profiles', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nombre público visible',
               existing_nullable=True)
    op.alter_column('profiles', 'full_name',
               existing_type=sa.VARCHAR(length=200),
               comment='Nombre completo legal',
               existing_nullable=True)
    op.alter_column('profiles', 'bio',
               existing_type=sa.TEXT(),
               comment='Biografía o descripción personal',
               existing_nullable=True)
    op.alter_column('profiles', 'avatar_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL de la imagen de perfil',
               existing_nullable=True)
    op.alter_column('profiles', 'preferred_language',
               existing_type=sa.VARCHAR(length=10),
               comment='Código de idioma (es, en, etc)',
               existing_nullable=False,
               existing_server_default=sa.text("'es'::character varying"))
    op.alter_column('profiles', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               comment='Zona horaria del usuario',
               existing_nullable=False,
               existing_server_default=sa.text("'UTC'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Zona horaria del usuario',
               existing_nullable=False,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('profiles', 'preferred_language',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Código de idioma (es, en, etc)',
               existing_nullable=False,
               existing_server_default=sa.text("'es'::character varying"))
    op.alter_column('profiles', 'avatar_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='URL de la imagen de perfil',
               existing_nullable=True)
    op.alter_column('profiles', 'bio',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Biografía o descripción personal',
               existing_nullable=True)
    op.alter_column('profiles', 'full_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Nombre completo legal',
               existing_nullable=True)
    op.alter_column('profiles', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nombre público visible',
               existing_nullable=True)
    op.drop_table('video')
    # ### end Alembic commands ###
