"""add audio table

Revision ID: de48711ac648
Revises: 3e8a83906bdf
Create Date: 2026-02-25 15:13:50.077283

"""
from alembic import op
import sqlalchemy as sa


revision = 'de48711ac648'
down_revision = '3e8a83906bdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
