"""add oauth fields to user model

Revision ID: f14b135ae3cb
Revises: 1d11381e9cfe
Create Date: 2026-02-16 15:37:11.087046

"""
from alembic import op
import sqlalchemy as sa


revision = 'f14b135ae3cb'
down_revision = '1d11381e9cfe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nombre público visible',
               existing_nullable=True)
    op.alter_column('profiles', 'full_name',
               existing_type=sa.VARCHAR(length=200),
               comment='Nombre completo legal',
               existing_nullable=True)
    op.alter_column('profiles', 'bio',
               existing_type=sa.TEXT(),
               comment='Biografía o descripción personal',
               existing_nullable=True)
    op.alter_column('profiles', 'avatar_url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL de la imagen de perfil',
               existing_nullable=True)
    op.alter_column('profiles', 'preferred_language',
               existing_type=sa.VARCHAR(length=10),
               comment='Código de idioma (es, en, etc)',
               existing_nullable=False,
               existing_server_default=sa.text("'es'::character varying"))
    op.alter_column('profiles', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               comment='Zona horaria del usuario',
               existing_nullable=False,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.add_column('users', sa.Column('provider', sa.String(), nullable=False))
    op.add_column('users', sa.Column('provider_user_id', sa.String(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'provider_user_id')
    op.drop_column('users', 'provider')
    op.alter_column('profiles', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Zona horaria del usuario',
               existing_nullable=False,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('profiles', 'preferred_language',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Código de idioma (es, en, etc)',
               existing_nullable=False,
               existing_server_default=sa.text("'es'::character varying"))
    op.alter_column('profiles', 'avatar_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='URL de la imagen de perfil',
               existing_nullable=True)
    op.alter_column('profiles', 'bio',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Biografía o descripción personal',
               existing_nullable=True)
    op.alter_column('profiles', 'full_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Nombre completo legal',
               existing_nullable=True)
    op.alter_column('profiles', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nombre público visible',
               existing_nullable=True)
    # ### end Alembic commands ###
